name: Check Nuxt.js Generate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Specify the versions of Node.js to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm install

      - name: Generate Nuxt.js project
        run: npm run generate
        env:
          NUXT_APP_AESKEY: ${{ secrets.NUXT_APP_AESKEY }}
          NUXT_BACKEND_PASSWORD: ${{ secrets.NUXT_BACKEND_PASSWORD }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          
          
